server:
  port: 9090

spring:
  application:
    name: legacy-system-with-contexa
  datasource:
    url: jdbc:postgresql://localhost:5432/identity
    username: admin
    password: 1111
    driver-class-name: org.postgresql.Driver
  thymeleaf:
    cache: false

  auth:
    urls:
      factors:
        passkey:
          rp-id: localhost
          rp-name: Contexa Security
          allowed-origins: http://localhost:9090
  ai:
    ollama:
      base-url: http://127.0.0.1:11434
      embedding:
        enabled: true
        model: mxbai-embed-large
      chat:
        options:
          model: qwen2.5:7b
          keep-alive: "24h"
    openai:
      api-key: ${OPENAI_API_KEY:}
      base-url: https://api.openai.com
      chat:
        options:
          model: gpt-4o-mini
          temperature: 0.3
        enabled: true
      embedding:
        enabled: false
        options:
          model: text-embedding-3-small

    anthropic:
      api-key: ${ANTHROPIC_API_KEY:your-anthropic-api-key}
      chat:
        enabled: false

  zero-trust:
    enabled: true
    ai:
      chat:
        model:
          priority: openai,ollama

logging:
  level:
    io.contexa: INFO
    io.contexa.contexaexamplelegacysystem: DEBUG
