-- Contexa DDL - Auto-generated by contexa init
CREATE EXTENSION IF NOT EXISTS vector;
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE users (
    id                      BIGSERIAL PRIMARY KEY,
    username                VARCHAR(100) NOT NULL UNIQUE,
    email                   VARCHAR(255) NOT NULL UNIQUE,
    password                VARCHAR(255) NOT NULL,
    name                    VARCHAR(100) NOT NULL,
    phone                   VARCHAR(20),
    department              VARCHAR(100),
    position                VARCHAR(100),
    profile_image_url       VARCHAR(500),
    enabled                 BOOLEAN DEFAULT TRUE NOT NULL,
    account_locked          BOOLEAN DEFAULT FALSE NOT NULL,
    credentials_expired     BOOLEAN DEFAULT FALSE NOT NULL,
    failed_login_attempts   INTEGER DEFAULT 0 NOT NULL,
    lock_expires_at         TIMESTAMP(6),
    mfa_enabled             BOOLEAN DEFAULT FALSE NOT NULL,
    preferred_mfa_factor    VARCHAR(50),
    last_used_mfa_factor    VARCHAR(50),
    last_mfa_used_at        TIMESTAMP(6),
    last_login_at           TIMESTAMP(6),
    last_login_ip           VARCHAR(45),
    password_changed_at     TIMESTAMP(6),
    locale                  VARCHAR(10) DEFAULT 'ko',
    timezone                VARCHAR(50) DEFAULT 'Asia/Seoul',
    created_at              TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at              TIMESTAMP(6)
);
CREATE INDEX idx_users_email ON users (email);
CREATE INDEX idx_users_department ON users (department);
CREATE INDEX idx_users_enabled ON users (enabled);

CREATE TABLE app_group (
    group_id    BIGSERIAL PRIMARY KEY,
    group_name  VARCHAR(100) NOT NULL UNIQUE,
    description VARCHAR(500),
    enabled     BOOLEAN DEFAULT TRUE NOT NULL,
    created_at  TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at  TIMESTAMP(6),
    created_by  VARCHAR(100)
);

CREATE TABLE role (
    role_id       BIGSERIAL PRIMARY KEY,
    role_name     VARCHAR(100) NOT NULL UNIQUE,
    role_desc     VARCHAR(500),
    is_expression BOOLEAN DEFAULT FALSE NOT NULL,
    enabled       BOOLEAN DEFAULT TRUE NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP(6),
    created_by    VARCHAR(100)
);

CREATE TABLE managed_resource (
    id                          BIGSERIAL PRIMARY KEY,
    resource_identifier         VARCHAR(512) NOT NULL UNIQUE,
    resource_type               VARCHAR(100) NOT NULL,
    http_method                 VARCHAR(10),
    friendly_name               VARCHAR(255),
    description                 VARCHAR(1024),
    service_owner               VARCHAR(100),
    parameter_types             VARCHAR(255),
    return_type                 VARCHAR(255),
    api_docs_url                VARCHAR(500),
    source_code_location        VARCHAR(500),
    status                      VARCHAR(50) DEFAULT 'NEEDS_DEFINITION' NOT NULL,
    created_at                  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at                  TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    available_context_variables VARCHAR(1024)
);

CREATE TABLE permission (
    permission_id        BIGSERIAL PRIMARY KEY,
    permission_name      VARCHAR(255) NOT NULL UNIQUE,
    friendly_name        VARCHAR(255),
    description          VARCHAR(1024),
    target_type          VARCHAR(100),
    action_type          VARCHAR(100),
    condition_expression VARCHAR(2048),
    managed_resource_id  BIGINT UNIQUE REFERENCES managed_resource ON DELETE SET NULL,
    created_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMP(6)
);

CREATE TABLE user_groups (
    user_id     BIGINT NOT NULL REFERENCES users ON DELETE CASCADE,
    group_id    BIGINT NOT NULL REFERENCES app_group ON DELETE CASCADE,
    assigned_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by VARCHAR(100),
    PRIMARY KEY (user_id, group_id)
);

CREATE TABLE group_roles (
    group_id    BIGINT NOT NULL REFERENCES app_group ON DELETE CASCADE,
    role_id     BIGINT NOT NULL REFERENCES role ON DELETE CASCADE,
    assigned_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by VARCHAR(100),
    PRIMARY KEY (group_id, role_id)
);

CREATE TABLE role_permissions (
    role_id       BIGINT NOT NULL REFERENCES role ON DELETE CASCADE,
    permission_id BIGINT NOT NULL REFERENCES permission ON DELETE CASCADE,
    assigned_at   TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    assigned_by   VARCHAR(100),
    PRIMARY KEY (role_id, permission_id)
);

CREATE TABLE policy (
    id                   BIGSERIAL PRIMARY KEY,
    name                 VARCHAR(255) NOT NULL UNIQUE,
    description          VARCHAR(255),
    effect               VARCHAR(255) NOT NULL,
    priority             INTEGER NOT NULL,
    friendly_description VARCHAR(2048),
    ai_model             VARCHAR(255),
    approval_status      VARCHAR(50) CHECK (approval_status IN ('PENDING','APPROVED','REJECTED','NOT_REQUIRED')),
    approved_at          TIMESTAMP(6),
    approved_by          VARCHAR(255),
    confidence_score     DOUBLE PRECISION,
    source               VARCHAR(50) CHECK (source IN ('MANUAL','AI_GENERATED','AI_EVOLVED','IMPORTED')),
    updated_at           TIMESTAMP(6),
    created_at           TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_active            BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE policy_target (
    id                BIGSERIAL PRIMARY KEY,
    policy_id         BIGINT NOT NULL REFERENCES policy ON DELETE CASCADE,
    target_type       VARCHAR(255) NOT NULL,
    target_identifier VARCHAR(255) NOT NULL,
    http_method       VARCHAR(255)
);

CREATE TABLE policy_rule (
    id          BIGSERIAL PRIMARY KEY,
    policy_id   BIGINT NOT NULL REFERENCES policy ON DELETE CASCADE,
    description VARCHAR(255)
);

CREATE TABLE policy_condition (
    id                   BIGSERIAL PRIMARY KEY,
    rule_id              BIGINT NOT NULL REFERENCES policy_rule ON DELETE CASCADE,
    condition_expression VARCHAR(2048) NOT NULL,
    authorization_phase  VARCHAR(255) DEFAULT 'PRE_AUTHORIZE' NOT NULL,
    description          VARCHAR(255)
);

CREATE TABLE role_hierarchy_config (
    hierarchy_id     BIGSERIAL PRIMARY KEY,
    description      VARCHAR(500),
    hierarchy_string TEXT NOT NULL UNIQUE,
    is_active        BOOLEAN DEFAULT FALSE NOT NULL
);

CREATE TABLE audit_log (
    id                  BIGSERIAL PRIMARY KEY,
    timestamp           TIMESTAMP(6) DEFAULT CURRENT_TIMESTAMP NOT NULL,
    principal_name      VARCHAR(255) NOT NULL,
    resource_identifier VARCHAR(512) NOT NULL,
    action              VARCHAR(255),
    decision            VARCHAR(255) NOT NULL,
    reason              VARCHAR(1024),
    client_ip           VARCHAR(45),
    details             TEXT,
    outcome             VARCHAR(255),
    resource_uri        VARCHAR(1024),
    session_id          VARCHAR(255),
    correlation_id      VARCHAR(64),
    event_category      VARCHAR(50),
    event_source        VARCHAR(50),
    http_method         VARCHAR(10),
    request_uri         VARCHAR(2048),
    risk_score          DOUBLE PRECISION,
    user_agent          VARCHAR(512)
);

CREATE TABLE business_resource (
    id            BIGSERIAL PRIMARY KEY,
    name          VARCHAR(255) NOT NULL UNIQUE,
    resource_type VARCHAR(255) NOT NULL,
    description   VARCHAR(1024)
);

CREATE TABLE business_action (
    id          BIGSERIAL PRIMARY KEY,
    name        VARCHAR(255) NOT NULL UNIQUE,
    action_type VARCHAR(255) NOT NULL,
    description VARCHAR(1024)
);

CREATE TABLE business_resource_action (
    business_resource_id   BIGINT NOT NULL REFERENCES business_resource ON DELETE CASCADE,
    business_action_id     BIGINT NOT NULL REFERENCES business_action ON DELETE CASCADE,
    mapped_permission_name VARCHAR(255) NOT NULL,
    PRIMARY KEY (business_resource_id, business_action_id)
);

CREATE TABLE condition_template (
    id                    BIGSERIAL PRIMARY KEY,
    name                  VARCHAR(255) NOT NULL UNIQUE,
    spel_template         VARCHAR(2048) NOT NULL,
    category              VARCHAR(255),
    parameter_count       INTEGER DEFAULT 0 NOT NULL,
    description           VARCHAR(1024),
    required_target_type  VARCHAR(1024),
    created_at            TIMESTAMP(6),
    is_auto_generated     BOOLEAN,
    is_universal          BOOLEAN,
    source_method         VARCHAR(255),
    template_type         VARCHAR(255),
    updated_at            TIMESTAMP(6),
    approval_required     BOOLEAN,
    classification        VARCHAR(255) CHECK (classification IN ('UNIVERSAL','CONTEXT_DEPENDENT','CUSTOM_COMPLEX')),
    complexity_score      INTEGER,
    context_dependent     BOOLEAN
);

CREATE TABLE wizard_session (
    session_id    VARCHAR(36) NOT NULL PRIMARY KEY,
    context_data  TEXT NOT NULL,
    owner_user_id VARCHAR(255) NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    expires_at    TIMESTAMP(6) NOT NULL
);

CREATE TABLE function_group (
    id   BIGSERIAL PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE function_catalog (
    id                  BIGSERIAL PRIMARY KEY,
    description         VARCHAR(1024),
    friendly_name       VARCHAR(255) NOT NULL,
    status              VARCHAR(50) NOT NULL CHECK (status IN ('UNCONFIRMED','ACTIVE','INACTIVE')),
    function_group_id   BIGINT REFERENCES function_group,
    managed_resource_id BIGINT NOT NULL UNIQUE REFERENCES managed_resource
);

CREATE TABLE policy_template (
    id                BIGSERIAL PRIMARY KEY,
    category          VARCHAR(255),
    description       VARCHAR(1024),
    name              VARCHAR(255) NOT NULL,
    policy_draft_json JSONB NOT NULL,
    template_id       VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE vector_store (
    id        UUID DEFAULT gen_random_uuid() NOT NULL PRIMARY KEY,
    content   TEXT NOT NULL,
    metadata  JSONB,
    embedding vector(1024)
);
CREATE INDEX vector_store_embedding_idx ON vector_store USING hnsw (embedding vector_cosine_ops);

CREATE TABLE user_behavior_profiles (
    id                      BIGSERIAL PRIMARY KEY,
    cluster_centroid_vector  TEXT,
    cluster_size             INTEGER,
    common_activities        JSON,
    common_ip_ranges         JSON,
    confidence_score         REAL,
    last_updated             TIMESTAMP(6),
    learning_count           INTEGER,
    normal_range_metadata    JSON,
    profile_type             VARCHAR(50) NOT NULL,
    user_id                  VARCHAR(255) NOT NULL,
    vector_cluster_id        VARCHAR(255)
);

CREATE TABLE soar_incidents (
    id           UUID NOT NULL PRIMARY KEY,
    created_at   TIMESTAMP(6) NOT NULL,
    history      TEXT,
    severity     VARCHAR(255),
    status       VARCHAR(255) NOT NULL CHECK (status IN ('NEW','TRIAGE','INVESTIGATION','PLANNING','PENDING_APPROVAL','EXECUTION','REPORTING','COMPLETED','AUTO_CLOSED','FAILED','CLOSED_BY_ADMIN')),
    title        VARCHAR(255) NOT NULL,
    updated_at   TIMESTAMP(6) NOT NULL,
    description  TEXT,
    incident_id  VARCHAR(255),
    metadata     TEXT,
    type         VARCHAR(255)
);

CREATE TABLE soar_approval_policies (
    id                      BIGSERIAL PRIMARY KEY,
    action_name             VARCHAR(255),
    auto_approve_on_timeout BOOLEAN NOT NULL,
    policy_name             VARCHAR(255) NOT NULL UNIQUE,
    required_approvers      INTEGER NOT NULL,
    required_roles          TEXT,
    severity                VARCHAR(255),
    timeout_minutes         INTEGER NOT NULL
);

CREATE TABLE soar_approval_requests (
    id                        BIGSERIAL PRIMARY KEY,
    action_name               VARCHAR(255) NOT NULL,
    created_at                TIMESTAMP(6) NOT NULL,
    description               TEXT,
    organization_id           VARCHAR(255),
    parameters                TEXT,
    playbook_instance_id      VARCHAR(255) NOT NULL,
    required_approvers        INTEGER,
    required_roles            TEXT,
    reviewer_comment          TEXT,
    reviewer_id               VARCHAR(255),
    status                    VARCHAR(255) NOT NULL,
    updated_at                TIMESTAMP(6) NOT NULL,
    request_id                VARCHAR(255) NOT NULL UNIQUE,
    action_type               VARCHAR(255),
    approval_comment          TEXT,
    approval_timeout          INTEGER,
    approval_type             VARCHAR(255),
    approved_at               TIMESTAMP(6),
    approved_by               VARCHAR(255),
    incident_id               VARCHAR(255),
    requested_by              VARCHAR(255),
    risk_level                VARCHAR(255),
    session_id                VARCHAR(255),
    tool_name                 VARCHAR(255),
    approved_count            INTEGER,
    rejected_count            INTEGER,
    remaining_approvals       INTEGER,
    quorum_satisfied          BOOLEAN DEFAULT FALSE,
    current_step_number       INTEGER,
    total_steps               INTEGER,
    reopened_from_request_id  VARCHAR(255),
    break_glass_requested     BOOLEAN DEFAULT FALSE,
    break_glass_reason        TEXT
);

CREATE TABLE soar_approval_steps (
    id                  BIGSERIAL PRIMARY KEY,
    request_id          VARCHAR(100) NOT NULL,
    step_number         INTEGER NOT NULL,
    step_name           VARCHAR(150) NOT NULL,
    status              VARCHAR(30) NOT NULL,
    required_approvers  INTEGER NOT NULL,
    approved_count      INTEGER NOT NULL,
    rejected_count      INTEGER NOT NULL,
    remaining_approvals INTEGER NOT NULL,
    required_roles      TEXT,
    opened_at           TIMESTAMP(6),
    completed_at        TIMESTAMP(6),
    created_at          TIMESTAMP(6) NOT NULL,
    updated_at          TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_soar_approval_step_request_number UNIQUE (request_id, step_number)
);

CREATE INDEX idx_soar_approval_step_request_id ON soar_approval_steps (request_id);
CREATE INDEX idx_soar_approval_step_status ON soar_approval_steps (status);

CREATE TABLE soar_approval_assignments (
    id                BIGSERIAL PRIMARY KEY,
    request_id        VARCHAR(100) NOT NULL,
    step_number       INTEGER NOT NULL,
    assignee_id       VARCHAR(100),
    assignee_role     VARCHAR(100),
    status            VARCHAR(30) NOT NULL,
    assigned_by       VARCHAR(100),
    assigned_at       TIMESTAMP(6),
    responded_at      TIMESTAMP(6),
    response_decision VARCHAR(30),
    response_comment  TEXT,
    created_at        TIMESTAMP(6) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL
);

CREATE INDEX idx_soar_approval_assignment_request_id ON soar_approval_assignments (request_id);
CREATE INDEX idx_soar_approval_assignment_status ON soar_approval_assignments (status);
CREATE INDEX idx_soar_approval_assignment_step ON soar_approval_assignments (request_id, step_number);

CREATE TABLE soar_approval_votes (
    id            BIGSERIAL PRIMARY KEY,
    request_id    VARCHAR(100) NOT NULL,
    approver_id   VARCHAR(100) NOT NULL,
    approver_name VARCHAR(150),
    approver_role VARCHAR(100) NOT NULL,
    decision      VARCHAR(20) NOT NULL,
    comment       TEXT,
    step_number   INTEGER NOT NULL,
    created_at    TIMESTAMP(6) NOT NULL,
    updated_at    TIMESTAMP(6) NOT NULL,
    CONSTRAINT uk_soar_approval_vote_request_approver_step UNIQUE (request_id, approver_id, step_number)
);

CREATE INDEX idx_soar_approval_vote_request_id ON soar_approval_votes (request_id);
CREATE INDEX idx_soar_approval_vote_decision ON soar_approval_votes (decision);
CREATE INDEX idx_soar_approval_vote_created_at ON soar_approval_votes (created_at);
CREATE INDEX idx_soar_approval_vote_request_step ON soar_approval_votes (request_id, step_number);

CREATE TABLE approval_notifications (
    id                BIGSERIAL PRIMARY KEY,
    action_required   BOOLEAN NOT NULL,
    action_url        VARCHAR(500),
    created_at        TIMESTAMP(6) NOT NULL,
    expires_at        TIMESTAMP(6),
    group_id          VARCHAR(100),
    is_read           BOOLEAN NOT NULL,
    message           TEXT,
    notification_data TEXT,
    notification_type VARCHAR(50) NOT NULL,
    priority          VARCHAR(20),
    read_at           TIMESTAMP(6),
    read_by           VARCHAR(100),
    request_id        VARCHAR(100) NOT NULL,
    target_role       VARCHAR(50),
    title             VARCHAR(255) NOT NULL,
    updated_at        TIMESTAMP(6) NOT NULL,
    user_id           VARCHAR(100)
);
CREATE INDEX idx_notification_request_id ON approval_notifications (request_id);
CREATE INDEX idx_notification_user_id ON approval_notifications (user_id);
CREATE INDEX idx_notification_is_read ON approval_notifications (is_read);
CREATE INDEX idx_notification_created_at ON approval_notifications (created_at);

CREATE TABLE threat_indicators (
    indicator_id         VARCHAR(255) NOT NULL PRIMARY KEY,
    active               BOOLEAN,
    campaign             VARCHAR(255),
    campaign_id          VARCHAR(255),
    cis_control          VARCHAR(255),
    confidence           DOUBLE PRECISION,
    created_at           TIMESTAMP(6) NOT NULL,
    description          TEXT,
    detected_at          TIMESTAMP(6),
    detection_count      INTEGER,
    expires_at           TIMESTAMP(6),
    false_positive_count INTEGER,
    first_seen           TIMESTAMP(6),
    last_seen            TIMESTAMP(6),
    malware_family       VARCHAR(255),
    mitre_attack_id      VARCHAR(255),
    mitre_tactic         VARCHAR(255),
    mitre_technique      VARCHAR(255),
    nist_csf_category    VARCHAR(255),
    severity             VARCHAR(255) NOT NULL CHECK (severity IN ('CRITICAL','HIGH','MEDIUM','LOW','INFO')),
    source               VARCHAR(255),
    status               VARCHAR(255) CHECK (status IN ('ACTIVE','INACTIVE','EXPIRED','FALSE_POSITIVE','UNDER_REVIEW')),
    threat_actor         VARCHAR(255),
    threat_actor_id      VARCHAR(255),
    threat_score         DOUBLE PRECISION,
    indicator_type       VARCHAR(255) NOT NULL CHECK (indicator_type IN ('IP_ADDRESS','DOMAIN','URL','FILE_HASH','FILE_PATH','REGISTRY_KEY','PROCESS_NAME','EMAIL_ADDRESS','USER_AGENT','CERTIFICATE','MUTEX','YARA_RULE','BEHAVIORAL','UNKNOWN','PATTERN','USER_ACCOUNT','COMPLIANCE','EVENT')),
    updated_at           TIMESTAMP(6),
    indicator_value      VARCHAR(255) NOT NULL
);

CREATE TABLE indicator_metadata (
    indicator_id VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    meta_value   VARCHAR(255),
    meta_key     VARCHAR(255) NOT NULL,
    PRIMARY KEY (indicator_id, meta_key)
);

CREATE TABLE indicator_tags (
    indicator_id VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    tag          VARCHAR(255)
);

CREATE TABLE related_indicators (
    indicator_id         VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    related_indicator_id VARCHAR(255) NOT NULL REFERENCES threat_indicators,
    PRIMARY KEY (indicator_id, related_indicator_id)
);

CREATE TABLE blocked_user (
    id                   BIGSERIAL PRIMARY KEY,
    block_count          INTEGER NOT NULL,
    blocked_at           TIMESTAMP(6) NOT NULL,
    confidence           DOUBLE PRECISION,
    reasoning            TEXT,
    request_id           VARCHAR(255) NOT NULL UNIQUE,
    resolve_reason       TEXT,
    resolved_action      VARCHAR(255),
    resolved_at          TIMESTAMP(6),
    resolved_by          VARCHAR(255),
    risk_score           DOUBLE PRECISION,
    source_ip            VARCHAR(45),
    status               VARCHAR(50) NOT NULL CHECK (status IN ('BLOCKED','UNBLOCK_REQUESTED','RESOLVED','TIMEOUT_RESPONDED','MFA_FAILED')),
    user_agent           VARCHAR(512),
    user_id              VARCHAR(100) NOT NULL,
    username             VARCHAR(100),
    unblock_requested_at TIMESTAMP(6),
    unblock_reason       TEXT,
    mfa_verified         BOOLEAN,
    mfa_verified_at      TIMESTAMP(6)
);

CREATE TABLE oauth2_authorization (
    id                            VARCHAR(100) NOT NULL PRIMARY KEY,
    registered_client_id          VARCHAR(100) NOT NULL,
    principal_name                VARCHAR(200) NOT NULL,
    authorization_grant_type      VARCHAR(100) NOT NULL,
    authorized_scopes             VARCHAR(1000),
    attributes                    TEXT,
    state                         VARCHAR(500),
    authorization_code_value      TEXT,
    authorization_code_issued_at  TIMESTAMP,
    authorization_code_expires_at TIMESTAMP,
    authorization_code_metadata   TEXT,
    access_token_value            TEXT,
    access_token_issued_at        TIMESTAMP,
    access_token_expires_at       TIMESTAMP,
    access_token_metadata         TEXT,
    access_token_type             VARCHAR(100),
    access_token_scopes           VARCHAR(1000),
    oidc_id_token_value           TEXT,
    oidc_id_token_issued_at       TIMESTAMP,
    oidc_id_token_expires_at      TIMESTAMP,
    oidc_id_token_metadata        TEXT,
    refresh_token_value           TEXT,
    refresh_token_issued_at       TIMESTAMP,
    refresh_token_expires_at      TIMESTAMP,
    refresh_token_metadata        TEXT,
    user_code_value               TEXT,
    user_code_issued_at           TIMESTAMP,
    user_code_expires_at          TIMESTAMP,
    user_code_metadata            TEXT,
    device_code_value             TEXT,
    device_code_issued_at         TIMESTAMP,
    device_code_expires_at        TIMESTAMP,
    device_code_metadata          TEXT
);

CREATE TABLE oauth2_registered_client (
    id                            VARCHAR(100) NOT NULL PRIMARY KEY,
    client_id                     VARCHAR(100) NOT NULL,
    client_id_issued_at           TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    client_secret                 VARCHAR(200),
    client_secret_expires_at      TIMESTAMP,
    client_name                   VARCHAR(200) NOT NULL,
    client_authentication_methods VARCHAR(1000) NOT NULL,
    authorization_grant_types     VARCHAR(1000) NOT NULL,
    redirect_uris                 VARCHAR(1000),
    post_logout_redirect_uris     VARCHAR(1000),
    scopes                        VARCHAR(1000) NOT NULL,
    client_settings               VARCHAR(2000) NOT NULL,
    token_settings                VARCHAR(2000) NOT NULL
);

CREATE TABLE user_credentials (
    credential_id                VARCHAR(1000) NOT NULL PRIMARY KEY,
    user_entity_user_id          VARCHAR(1000) NOT NULL,
    public_key                   BYTEA NOT NULL,
    signature_count              BIGINT,
    uv_initialized               BOOLEAN,
    backup_eligible              BOOLEAN NOT NULL,
    authenticator_transports     VARCHAR(1000),
    public_key_credential_type   VARCHAR(100),
    backup_state                 BOOLEAN NOT NULL,
    attestation_object           BYTEA,
    attestation_client_data_json BYTEA,
    created                      TIMESTAMP,
    last_used                    TIMESTAMP,
    label                        VARCHAR(1000) NOT NULL
);

CREATE TABLE user_entities (
    id           VARCHAR(1000) NOT NULL PRIMARY KEY,
    name         VARCHAR(100) NOT NULL,
    display_name VARCHAR(200)
);

CREATE TABLE one_time_tokens (
    token_value VARCHAR(36) NOT NULL PRIMARY KEY,
    username    VARCHAR(50) NOT NULL,
    expires_at  TIMESTAMP NOT NULL
);
